version: "2"
services:
  web: 
    build: .
    tty: true
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
        - "6379"
  db:
    image: postgres
