version: "2"
services:
  web: 
    build: .
    tty: true
    env_file:
      - app.env
    ports:
      - "8000:8000"
      - "8888:8888"
      - "35729:35729"
    volumes:
      - .:/var/www
      - /var/www/node_modules
    depends_on:
      - db
      - redis
    command: "./scripts/entrypoint.sh"

  redis:
    image: redis
    ports:
        - "6379"

  db:
    image: postgres
